---
abstract: 'Adds a quick-update comments portlet for the user summary and the rights ModifyUserComments and SeeUserComments'
author:
  - 'Thomas Sibley <trsibley@uw.edu>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: gplv2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RTx-QuickUpdateUserComments
no_index:
  directory:
    - html
    - inc
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.01
